name: 'Setup project'
description: 'Install dependencies and other project setup'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'
    - name: "Add Poetry to PATH"
      shell: bash
      run: echo "$POETRY_HOME/bin" >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash
      run: |
        poetry install
        VENV_PATH="$(poetry env info -p)"
        echo "$(VENV_PATH)/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$(VENV_PATH)" >> $GITHUB_ENV
