name: 'Setup project'
description: 'Install dependencies and other project setup'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - name: Set up Python
      uses: kolonialno/actions/setup-python@setup-python-3.2.2
      with:
        package-manager: 'poetry'
        tool-versions-path: .tool-versions
    - name: Create venv
      shell: bash
      run: python -m venv .venv
    - name: Install dependencies
      shell: bash
      run: poetry install --remove-untracked
