# Workflow to build and release a new version
name: Release to PyPI

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run CI checks
        run: poetry run make
      - name: Build package
        run: poetry build
      - name: Create GitHub release
        run: poetry run ./bin/create-github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Publish package to PyPI
#        run: poetry publish --username=__token__ --password="${{ secrets.PYPI_API_TOKEN }}"
